/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kriptografi;

/**
 *
 * @author maulv
 */
public class Polyalphbetik2Key extends javax.swing.JFrame {

    /**
     * Creates new form Polyalphbetik2Key
     */
    public Polyalphbetik2Key() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPoly2Enkripsi = new javax.swing.JLabel();
        javax.swing.JTextField eInputPolyPlain2 = new javax.swing.JTextField();
        eLblPoly2Plain = new javax.swing.JLabel();
        eLblPoly2Kunci1 = new javax.swing.JLabel();
        eInputPoly2Kunci2 = new javax.swing.JTextField();
        dBtnPoly2Dekripsi = new javax.swing.JButton();
        eInputPolyChiper2 = new javax.swing.JTextField();
        eLblPoly2Chiper = new javax.swing.JLabel();
        dLblPoly2Plain = new javax.swing.JLabel();
        dInputPolyPlain2 = new javax.swing.JTextField();
        dInputPoly2Kunci1 = new javax.swing.JTextField();
        dLblPoly2Kunci1 = new javax.swing.JLabel();
        dLblPoly2Chiper = new javax.swing.JLabel();
        dInputPolyChiper2 = new javax.swing.JTextField();
        lblPoly2Dekripsi = new javax.swing.JLabel();
        eBtnPoly2Enkirpsi1 = new javax.swing.JButton();
        eInputPoly2Kunci1 = new javax.swing.JTextField();
        eLblPoly2Kunci2 = new javax.swing.JLabel();
        dInputPoly2Kunci2 = new javax.swing.JTextField();
        dLblPoly2Kunci2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPoly2Enkripsi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPoly2Enkripsi.setText("Enkripsi Teknik Polyalphabetical");

        eInputPolyPlain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eInputPolyPlain2ActionPerformed(evt);
            }
        });

        eLblPoly2Plain.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eLblPoly2Plain.setText("Plain Teks");

        eLblPoly2Kunci1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eLblPoly2Kunci1.setText("Kunci 1");

        dBtnPoly2Dekripsi.setText("Proses");
        dBtnPoly2Dekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBtnPoly2DekripsiActionPerformed(evt);
            }
        });

        eLblPoly2Chiper.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eLblPoly2Chiper.setText("Chiper Teks");

        dLblPoly2Plain.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dLblPoly2Plain.setText("Chiper Teks");

        dLblPoly2Kunci1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dLblPoly2Kunci1.setText("Kunci 1");

        dLblPoly2Chiper.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dLblPoly2Chiper.setText("Plain Teks");

        lblPoly2Dekripsi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPoly2Dekripsi.setText("Dekripsi Teknik Polyalphabetical");

        eBtnPoly2Enkirpsi1.setText("Proses");
        eBtnPoly2Enkirpsi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBtnPoly2Enkirpsi1ActionPerformed(evt);
            }
        });

        eLblPoly2Kunci2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eLblPoly2Kunci2.setText("Kunci 2");

        dLblPoly2Kunci2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dLblPoly2Kunci2.setText("Kunci 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblPoly2Enkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eLblPoly2Plain)
                                    .addComponent(eLblPoly2Kunci1))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(eLblPoly2Kunci2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eInputPolyPlain2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eInputPoly2Kunci1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eInputPoly2Kunci2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eBtnPoly2Enkirpsi1))))
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eLblPoly2Chiper)
                .addGap(22, 22, 22)
                .addComponent(eInputPolyChiper2)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblPoly2Dekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dLblPoly2Kunci1)
                            .addComponent(dLblPoly2Chiper)
                            .addComponent(dLblPoly2Kunci2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dInputPoly2Kunci1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dInputPolyChiper2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dBtnPoly2Dekripsi)
                            .addComponent(dInputPoly2Kunci2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dLblPoly2Plain)
                        .addGap(18, 18, 18)
                        .addComponent(dInputPolyPlain2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPoly2Enkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eInputPolyPlain2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(eLblPoly2Plain))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eLblPoly2Kunci1)
                    .addComponent(eInputPoly2Kunci1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eInputPoly2Kunci2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(eLblPoly2Kunci2))
                .addGap(18, 18, 18)
                .addComponent(eBtnPoly2Enkirpsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eInputPolyChiper2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eLblPoly2Chiper))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPoly2Dekripsi)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dInputPolyPlain2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dLblPoly2Plain))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLblPoly2Kunci1)
                    .addComponent(dInputPoly2Kunci1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dInputPoly2Kunci2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dLblPoly2Kunci2))
                .addGap(18, 18, 18)
                .addComponent(dBtnPoly2Dekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLblPoly2Chiper)
                    .addComponent(dInputPolyChiper2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eInputPolyPlain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eInputPolyPlain2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eInputPolyPlain2ActionPerformed

    private void dBtnPoly2DekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBtnPoly2DekripsiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dBtnPoly2DekripsiActionPerformed

    private void eBtnPoly2Enkirpsi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBtnPoly2Enkirpsi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eBtnPoly2Enkirpsi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
         eBtnPoly2Enkirpsiging.Logger.getLogger(Polyalphbetik2Key.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Polyalphbetik2Key.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Polyalphbetik2Key.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Polyalphbetik2Key.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Polyalphbetik2Key().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dBtnPoly2Dekripsi;
    private javax.swing.JTextField dInputPoly2Kunci1;
    private javax.swing.JTextField dInputPoly2Kunci2;
    private javax.swing.JTextField dInputPolyChiper2;
    private javax.swing.JTextField dInputPolyPlain2;
    private javax.swing.JLabel dLblPoly2Chiper;
    private javax.swing.JLabel dLblPoly2Kunci1;
    private javax.swing.JLabel dLblPoly2Kunci2;
    private javax.swing.JLabel dLblPoly2Plain;
    private javax.swing.JButton eBtnPoly2Enkirpsi1;
    private javax.swing.JTextField eInputPoly2Kunci1;
    private javax.swing.JTextField eInputPoly2Kunci2;
    private javax.swing.JTextField eInputPolyChiper2;
    private javax.swing.JLabel eLblPoly2Chiper;
    private javax.swing.JLabel eLblPoly2Kunci1;
    private javax.swing.JLabel eLblPoly2Kunci2;
    private javax.swing.JLabel eLblPoly2Plain;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPoly2Dekripsi;
    private javax.swing.JLabel lblPoly2Enkripsi;
    // End of variables declaration//GEN-END:variables
}
